version: '2.3'

services:
    batchnorm-run:
        image: mxnet-gpu-rel:latest
        build:
            context: ../dockerfiles
            dockerfile: mxnet-cu90.Dockerfile
        volumes:
            - .:/mnt
        runtime: nvidia
        working_dir: /mnt
        command: >
            bash -c "./main.py -b 128 -i 512"
        container_name: batchnorm-run
