
version: '2.3'

services:
    amp-vecadd:
        image: cmake-gpu:latest
        build:
            context: .
            dockerfile: cmake-cu90.Dockerfile
        volumes:
            - .:/mnt
        runtime: nvidia
        working_dir: /mnt
        command: >
            bash -c "set -e; 
                     mkdir -p build && cd build;
                     if [ ! -f \"Makefile\" ]; then 
                         cmake -DCMAKE_CUDA_FLAGS=\"-arch=compute_61\" ..;
                     fi 
                     make all;
                     chown -R $$(stat -c '%u:%g' /mnt) .;
                     ./bin/vecadd;"
        container_name: amp-vecadd
