name: Action2
description: Action2
runs:
  using: composite
  steps:
    - uses: ./.github/actions/action1
      with:
        some-input: 1
    - uses: ./.github/actions/action1
      with:
        some-input: 3
    - uses: ./.github/actions/action1
      with:
        some-input: 5
