version: '2.3'

services:
    jupyter-dev:
        image: jupyter:dev
        build:
            context: ./dockerfiles
            dockerfile: jupyter.Dockerfile
        network_mode: "host"
        runtime: nvidia
        volumes:
            - .:/mnt
        working_dir: /mnt
    nvvp:
        image: nvvp:11.2
        build:
            context: ./dockerfiles
            dockerfile: nvvp.Dockerfile
        network_mode: "host"
        environment:
            - DISPLAY=:0
        runtime: nvidia
        volumes:
            - .:/mnt
            - "~/.Xauthority:/root/.Xauthority:rw"
        working_dir: /mnt
        privileged: true
