version: '2.3'

services:
    fp16-vecadd:
        image: cmake-gpu:latest
        build:
            context: ../dockerfiles
            dockerfile: cmake-cu90.Dockerfile
        volumes:
            - .:/mnt
        runtime: nvidia
        working_dir: /mnt
        command: >
            bash -ce "mkdir -p build && cd build
                      if [ ! -f 'Makefile' ]; then 
                          cmake -DCMAKE_CUDA_FLAGS='-arch=compute_61' ..
                      fi 
                      make all
                      chown -R $$(stat -c '%u:%g' /mnt) ."
