name: MyAction
description: Happy happy
inputs:
  flag:
    description: Happy
    required: true
    default: ${{ false }}
runs:
  using: composite
  steps:
    - name: Run
      shell: bash
      run: |
        echo ${{ inputs.flag }}
        echo ${{ inputs.flag == 'true' }}
        echo ${{ inputs.flag == 'false' }}
        echo ${{ inputs.flag == 0 }}
        echo ${{ inputs.flag == 1 }}
    - name: Run 3
      shell: bash
      run: export ABC="123"
    - name: Run 4
      shell: bash
      run: echo $ABC
