name: CI
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_global_batch_size: [1024]
        include: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: |
          echo "${{ matrix.target_global_batch_size }}"
          echo "${{ matrix.project }}"
          echo "${{ matrix.config }}"
