name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      some-required-input:
        description: "hello"
        required: true
        type: string
      some-default-input:
        description: "hello yourself"
        required: false
        type: string
        default: "123"
jobs:
  myjob:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - run: |
          echo ${{ inputs.some-required-input }}
          echo ${{ inputs.some-default-input }}
      - uses: actions/checkout@v4
      - id: mystep
        run: |
          echo "123456" >> tmp.log
          cat tmp.log
          cat <<EOF > ${GITHUB_OUTPUT}
          var1=123
          var2=234
          EOF
      - run: |
          echo ${{ steps.mystep.outputs.var1 }}
          echo ${{ steps.mystep.outputs.var2 }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: |
          python --version
          python -V
          which python
      - id: step1
        run: echo "test=1" >> ${GITHUB_OUTPUT}
      - run: exit -1
      - id: step2
        run: echo "test=2" >> ${GITHUB_OUTPUT}
  myjob2:
    runs-on: ubuntu-latest
    needs: [myjob]
    if: ${{ always() && needs.myjob.outputs.output1 == 1 }}
    steps:
      - name: >-
          output1=${{ needs.myjob.outputs.output1
          }}, output2=${{
          needs.myjob.outputs.output2 }}
        uses: actions/checkout@v4
      - uses: ./.github/actions/action1
      - uses: ./.github/actions/action1
        continue-on-error: true
        with:
          some-input: something
      - uses: ./.github/actions/action1
        continue-on-error: true
        with:
          some-input: "something"
      - if: ${{ success() }}
        run: echo "success"
      - if: ${{ failure() }}
        run: echo "failure"
      - uses: ./.github/actions/action2
      - run: echo "PATH=${PATH}:${HOME}" >> ${GITHUB_ENV}
      - run: |
          cd ~
          touch run.sh
          chmod +x run.sh
      - run: |
          echo ${PATH}
          which run.sh
      - run: |
          echo ${{ needs.myjob.outputs.output1 }}
          echo ${{ needs.myjob.outputs.output1 == 1 }}
          echo ${{ needs.myjob.outputs.output1 == '1' }}
          echo ${{ needs.myjob.outputs.output2 }}
