name: CI
on: [push]
jobs:
  myjob:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: |
          python --version
          python -V
          which python
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
      - run: mkdir /tmp/pi-datasets
      - name: Mount datasets
        run: |
          gcsfuse pi-datasets /tmp/pi-datasets
