name: CI
on: [push]
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo  ${{ secrets.MY_SECRET }}
      - uses: ./.github/actions/myaction
        with:
          flag: false
      - uses: ./.github/actions/myaction
        with:
          flag: true
