name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      myflag:
        description: My flag.
        required: false
        type: boolean
        default: false
jobs:
  myjob0:
    runs-on: ubuntu-latest
    steps:
      - id: myoutput
        run: |
          echo ${{ inputs.myflag }}
      # - uses: actions/checkout@v4
  myjob1:
    uses: ./.github/workflows/reuseable.yml
    with:
      myflag: ${{ inputs.myflag }}
