name: CI
on:
  push:
    branches:
      - main
jobs:
  myjob0:
    runs-on: ubuntu-latest
    steps:
      - id: myoutput
        run: |
          echo "JSON_RESPONSE <<EOF" >> ${GITHUB_OUTPUT}
          echo "hello" >> ${GITHUB_OUTPUT}
          echo "myopia" >> ${GITHUB_OUTPUT}
          echo 'EOF' >> ${GITHUB_OUTPUT}
      - run: |
          echo ${{ steps.myoutput.outputs.JSON_RESPONSE }}
