name: CI
on: [push]
jobs:
  myjob:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: |
          python --version
          python -V
          which python
      - id: step1
        run: echo "test=1" >> ${GITHUB_OUTPUT}
      - run: exit -1
      - id: step2
        run: echo "test=2" >> ${GITHUB_OUTPUT}
  myjob2:
    runs-on: ubuntu-latest
    needs: [myjob]
    if: ${{ always() }}
    steps:
      - run: echo "PATH=${PATH}:${HOME}" >> ${GITHUB_ENV}
      - run: |
          touch run.sh
          chmod +x run.sh
      - run: |
          echo ${PATH}
          which run.sh
      - run: |
          echo ${{ needs.myjob.outputs.output1 }}
          echo ${{ needs.myjob.outputs.output1 == 1 }}
          echo ${{ needs.myjob.outputs.output1 == '1' }}
          echo ${{ needs.myjob.outputs.output2 }}
      - uses: ./.github/actions/action1
