name: CI
on: [push]
jobs:
  ci_pipeline_init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  ci_pipeline:
    needs: [ci_pipeline_init]
    runs-on: ubuntu-latest
    steps:
      - run: python3 ci-pipeline-descriptor.py
        id: generate_ci_pipeline
